default: &default
  adapter:   mysql2
  encoding:  utf8mb4
  charset:   utf8mb4
  collation: utf8mb4_general_ci
  pool:      <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:  <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password:  <%= ENV.fetch('DATABASE_PASSWORD') { nil } %>
  host:      <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port:      <%= ENV.fetch('DATABASE_PORT') { 3306 } %>

development: &development
  <<: *default
  database: appname_development

development_master:
  <<: *development

development_slave:
  <<: *development
  host: <%= ENV.fetch('DATABASE_SLAVE_HOST') { 'localhost' } %>


test: &test
  <<: *default
  database: appname_test

test_master:
  <<: *test

test_slave:
  <<: *test
  host: <%= ENV.fetch('DATABASE_SLAVE_HOST') { 'localhost' } %>

production:
  <<: *default
  database: appname_production
