default: &default
  adapter:  mysql2
  encoding: utf8
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USER') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { nil } %>
  host:     <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port:     <%= ENV.fetch('DATABASE_PORT') { 3306 } %>

development:
  <<: *default
  database: appname_development

test:
  <<: *default
  database: appname_test

production:
  <<: *default
  database: appname_production
