FROM mysql:5.7

RUN mkdir -p /var/log/mysql_slave
RUN touch /var/log/mysql_slave/mysql-bin.log
RUN chown -R mysql:mysql /var/log/mysql_slave

ADD ./db/slave.cnf /etc/mysql/conf.d
ADD ./db/slave.sh /docker-entrypoint-initdb.d

EXPOSE 3306
CMD ["mysqld"]
