FROM mysql:5.7

RUN mkdir -p /var/log/mysql_master
RUN touch /var/log/mysql_master/mysql-bin.log
RUN chown -R mysql:mysql /var/log/mysql_master

ADD ./db/master.cnf /etc/mysql/conf.d
ADD ./db/master.sh /docker-entrypoint-initdb.d

EXPOSE 3306
CMD ["mysqld"]
